[package]
name = "fhe16-wrapper"
version = "0.1.0"
edition = "2021"



[lib]
name = "fhe16_wrapper"
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/bin/demo.rs"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
libloading = "0.8"


